### PR TITLE
Change soap2r for soap4r-ng and use newer rubies

### PR DESCRIPTION
**Pull request by pschambacher**
@grosser 

Not the greatest test suite I've seen :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by grosser** [comment]
why the switch to soap4r-ng ?

**Comment by pschambacher** [comment]
soap2r isn't maintained and doesn't work on ruby 2.2

**Comment by grosser** [comment]
yeah, the docs/tests look pretty nice for soap4r-ng ...

**Comment by grosser** [comment]
I helped with the soap2r fork, so sad to see it go, but this looks pretty neat :)

**Comment by grosser** [comment]
:+1:

**Comment by pschambacher** [comment]
I have no permission here so I'll need you to merge, bump and release :stuck_out_tongue_winking_eye:

**Comment by grosser** [comment]
1.3.0

**Pull request merged**
